/** Shared UI for the deeper ITAD Core Job records. Brand is always passed explicitly by the consuming workspace. */
import { CheckCircle2, CircleAlert, DatabaseZap, Download, FileCheck2, History, LoaderCircle, MessageSquareText, PackagePlus, ShieldCheck, Upload, UserRoundCheck } from "lucide-react";
import { ChangeEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { fileToBase64, resolveItadContentType } from "@/lib/itadFiles";

type ItadBrand = "reborn" | "bulk_gsm";
type AssetCondition = "unassessed" | "working" | "repairable" | "parts_only" | "recycling";
type EvidenceType = "data_erasure" | "collection_manifest" | "reuse_outcome" | "recycling_outcome" | "other";

const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const formatCount = (value: number) => new Intl.NumberFormat("en-GB").format(value);

export function CoreJobRecordsPanel({ jobId, brand, workspace }: { jobId: number; brand: ItadBrand; workspace: "Reborn" | "Bulk GSM" }) {
  const utils = trpc.useUtils();
  const detailInput = useMemo(() => ({ jobId, brand }), [jobId, brand]);
  const detail = trpc.itadCore.detail.useQuery(detailInput);
  const [asset, setAsset] = useState({ assetCategory: "", manufacturer: "", model: "", assetTag: "", serialNumber: "", quantity: 1, condition: "unassessed" as AssetCondition, dataHandlingState: "not_recorded" as const });
  const [evidence, setEvidence] = useState({ evidenceType: "data_erasure" as EvidenceType, certificateReference: "", issuer: "", file: null as File | null });
  const [importBatch, setImportBatch] = useState({ importReference: "", file: null as File | null });
  const [lastMapping, setLastMapping] = useState<{ fieldMapping: Record<string, string | null>; sourceHeaders: string[]; exceptions: Array<{ rowNumber: number; message: string }> } | null>(null);
  const [comment, setComment] = useState("");
  const [exception, setException] = useState({ title: "", detail: "" });
  const refresh = () => utils.itadCore.detail.invalidate(detailInput);
  const addAsset = trpc.itadCore.addAsset.useMutation({ onSuccess: () => { refresh(); setAsset({ assetCategory: "", manufacturer: "", model: "", assetTag: "", serialNumber: "", quantity: 1, condition: "unassessed", dataHandlingState: "not_recorded" }); toast("Asset inventory row added"); }, onError: (error) => toast("Asset inventory was not saved", { description: error.message }) });
  const recordEvidence = trpc.itadCore.recordEvidence.useMutation({ onSuccess: () => { refresh(); setEvidence({ evidenceType: "data_erasure", certificateReference: "", issuer: "", file: null }); toast("Evidence record added", { description: "It remains internal until explicitly approved for the customer." }); }, onError: (error) => toast("Evidence record was not saved", { description: error.message }) });
  const importSecuraze = trpc.itadCore.importSecurazeCsv.useMutation({ onSuccess: ({ importBatch: batch, mapping }) => { refresh(); setImportBatch({ importReference: "", file: null }); setLastMapping(mapping); toast("Securaze CSV mapped", { description: `${batch.importedRecordCount} asset rows added; ${batch.exceptionCount} rows held as exceptions.` }); }, onError: (error) => toast("Securaze CSV was not imported", { description: error.message }) });
  const approveEvidence = trpc.itadCore.approveEvidence.useMutation({ onSuccess: () => { refresh(); toast("Evidence approved for customer portal"); }, onError: (error) => toast("Evidence could not be approved", { description: error.message }) });
  const addComment = trpc.itadCore.addComment.useMutation({ onSuccess: () => { refresh(); setComment(""); toast("Core Job comment added"); }, onError: (error) => toast("Comment could not be added", { description: error.message }) });
  const createException = trpc.itadCore.createException.useMutation({ onSuccess: () => { refresh(); setException({ title: "", detail: "" }); toast("Exception opened and assigned to you"); }, onError: (error) => toast("Exception could not be opened", { description: error.message }) });
  const updateException = trpc.itadCore.updateException.useMutation({ onSuccess: () => { refresh(); toast("Exception updated"); }, onError: (error) => toast("Exception could not be updated", { description: error.message }) });
  const downloadEvidence = trpc.itadCore.downloadEvidence.useMutation({ onSuccess: ({ url }) => window.open(url, "_blank", "noopener,noreferrer"), onError: (error) => toast("Evidence file could not be opened", { description: error.message }) });
  const readFile = (setter: (file: File | null) => void) => (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0] ?? null; if (file?.size && file.size > 10_000_000) { toast("File is too large", { description: "Use a file of 10 MB or less." }); event.target.value = ""; return; } setter(file); };
  const submitEvidence = async () => { try { const file = evidence.file ? { fileName: evidence.file.name, contentType: resolveItadContentType(evidence.file), contentBase64: await fileToBase64(evidence.file) } : undefined; recordEvidence.mutate({ jobId, brand, evidenceType: evidence.evidenceType, certificateReference: evidence.certificateReference || undefined, issuer: evidence.issuer || undefined, file }); } catch (error) { toast("Evidence file could not be read", { description: error instanceof Error ? error.message : "Try a different file." }); } };
  const submitImport = async () => { if (!importBatch.file) return; try { importSecuraze.mutate({ jobId, brand, importReference: importBatch.importReference || undefined, file: { fileName: importBatch.file.name, contentType: resolveItadContentType(importBatch.file), contentBase64: await fileToBase64(importBatch.file) } }); } catch (error) { toast("Securaze CSV could not be read", { description: error instanceof Error ? error.message : "Try a different file." }); } };

  if (detail.isLoading) return <section className="core-job-records core-job-loading"><LoaderCircle className="assessment-spin" size={19} />Opening Core Job records</section>;
  if (!detail.data) return <section className="core-job-records core-job-loading">Core Job records are not available right now.</section>;
  const { job, assets, evidence: evidenceRows, importBatches, comments, exceptions, activity } = detail.data;
  const totalAssets = assets.reduce((total, row) => total + row.quantity, 0);

  return <section className="core-job-records" aria-label={`${workspace} Core Job records`}>
    <header className="core-job-records-head"><div><p className="ops-kicker">ITAD CORE / JOB {job.jobReference}</p><h3>Inventory, evidence <em>and review.</em></h3><p>{workspace} controls these records in its own brand partition. A source CSV result remains review data, and customer portal visibility needs a separate operator approval.</p></div><div className="core-job-counts"><span><PackagePlus size={16} />{formatCount(totalAssets)} assets</span><span><FileCheck2 size={16} />{evidenceRows.length} evidence</span><span><DatabaseZap size={16} />{importBatches.length} imports</span></div></header>
    <div className="core-job-ledger">
      <section className="core-job-pane"><div className="core-pane-title"><PackagePlus size={18} /><div><p className="ops-kicker">ASSET INVENTORY</p><h4>Add a batch or identified asset</h4></div></div><div className="core-form-grid"><label>Asset category<input value={asset.assetCategory} onChange={(event) => setAsset({ ...asset, assetCategory: event.target.value })} placeholder="Laptop, mobile, monitor" /></label><label>Quantity<input type="number" min="1" value={asset.quantity} onChange={(event) => setAsset({ ...asset, quantity: Math.max(1, Number(event.target.value) || 1) })} /></label><label>Condition<select value={asset.condition} onChange={(event) => setAsset({ ...asset, condition: event.target.value as AssetCondition })}>{["unassessed", "working", "repairable", "parts_only", "recycling"].map((value) => <option key={value} value={value}>{titleCase(value)}</option>)}</select></label><label>Manufacturer<input value={asset.manufacturer} onChange={(event) => setAsset({ ...asset, manufacturer: event.target.value })} placeholder="Optional" /></label><label>Model<input value={asset.model} onChange={(event) => setAsset({ ...asset, model: event.target.value })} placeholder="Optional" /></label><label>Asset tag<input value={asset.assetTag} onChange={(event) => setAsset({ ...asset, assetTag: event.target.value })} placeholder="Optional" /></label><label className="core-wide">Serial number<input value={asset.serialNumber} onChange={(event) => setAsset({ ...asset, serialNumber: event.target.value })} placeholder="Optional — one row can also represent a quantity batch" /></label></div><button className="button button-dark" disabled={!asset.assetCategory || addAsset.isPending} onClick={() => addAsset.mutate({ jobId, brand, ...asset, manufacturer: asset.manufacturer || undefined, model: asset.model || undefined, assetTag: asset.assetTag || undefined, serialNumber: asset.serialNumber || undefined })}>{addAsset.isPending ? <LoaderCircle className="assessment-spin" size={16} /> : <PackagePlus size={16} />}Add inventory row</button><div className="core-row-list">{assets.length ? assets.map((row) => <article key={row.id}><strong>{row.quantity}× {row.assetCategory}</strong><span>{[row.manufacturer, row.model, row.assetTag, row.serialNumber].filter(Boolean).join(" · ") || "No identifier supplied"}</span><small>{row.sourceImportBatchId ? `Securaze row ${row.sourceRowNumber} · ` : ""}{titleCase(row.condition)} · {titleCase(row.dataHandlingState)}</small></article>) : <p>No structured assets recorded yet.</p>}</div></section>
      <section className="core-job-pane"><div className="core-pane-title"><ShieldCheck size={18} /><div><p className="ops-kicker">EVIDENCE CERTIFICATES</p><h4>Record, attach, then approve</h4></div></div><div className="core-form-grid"><label>Evidence type<select value={evidence.evidenceType} onChange={(event) => setEvidence({ ...evidence, evidenceType: event.target.value as EvidenceType })}>{["data_erasure", "collection_manifest", "reuse_outcome", "recycling_outcome", "other"].map((value) => <option key={value} value={value}>{titleCase(value)}</option>)}</select></label><label>Certificate reference<input value={evidence.certificateReference} onChange={(event) => setEvidence({ ...evidence, certificateReference: event.target.value })} placeholder="Optional reference" /></label><label className="core-wide">Issuer<input value={evidence.issuer} onChange={(event) => setEvidence({ ...evidence, issuer: event.target.value })} placeholder="Optional issuer" /></label><label className="core-file-input">Attach supporting file<input type="file" accept=".pdf,.csv,.xls,.xlsx,.docx,.jpg,.jpeg,.png" onChange={readFile((file) => setEvidence({ ...evidence, file }))} /><span>{evidence.file ? evidence.file.name : "Optional PDF, spreadsheet, Word or image"}</span></label></div><p className="core-caution">An operator must separately approve an attached record before it reaches the customer portal.</p><button className="button button-dark" disabled={recordEvidence.isPending} onClick={submitEvidence}>{recordEvidence.isPending ? <LoaderCircle className="assessment-spin" size={16} /> : <ShieldCheck size={16} />}Record evidence</button><div className="core-row-list">{evidenceRows.length ? evidenceRows.map((row) => <article key={row.id}><strong>{titleCase(row.evidenceType)}</strong><span>{[row.certificateReference, row.issuer].filter(Boolean).join(" · ") || "No certificate reference or issuer supplied"}</span><small><CheckCircle2 size={13} />{titleCase(row.verificationState)} · {row.customerApprovedAt ? "Customer approved" : "Internal review"}{row.fileName ? <button onClick={() => downloadEvidence.mutate({ evidenceId: row.id, jobId, brand })}><Download size={13} />{row.fileName}</button> : null}{row.fileName && !row.customerApprovedAt ? <button className="core-approve" onClick={() => approveEvidence.mutate({ evidenceId: row.id, jobId, brand })}><UserRoundCheck size={13} />Approve</button> : null}</small></article>) : <p>No evidence records have been added.</p>}</div></section>
      <section className="core-job-pane core-import-pane"><div className="core-pane-title"><DatabaseZap size={18} /><div><p className="ops-kicker">SECURAZE CSV MAPPER</p><h4>Map rows, hold exceptions</h4></div></div><p className="core-caution">CSV only. Required fields are serial number and result/status. Imported source results stay as review data, not an automatic erasure conclusion.</p><div className="core-form-grid"><label>Import reference<input value={importBatch.importReference} onChange={(event) => setImportBatch({ ...importBatch, importReference: event.target.value })} placeholder="Optional batch reference" /></label><label className="core-file-input core-wide">Securaze CSV export<input type="file" accept=".csv,text/csv" onChange={readFile((file) => setImportBatch({ ...importBatch, file }))} /><span>{importBatch.file ? importBatch.file.name : "Choose a UTF-8 CSV export"}</span></label></div><button className="button button-lime" disabled={!importBatch.file || importSecuraze.isPending} onClick={submitImport}>{importSecuraze.isPending ? <LoaderCircle className="assessment-spin" size={16} /> : <Upload size={16} />}Map and import Securaze CSV</button>{lastMapping ? <div className="core-mapping-result"><strong>Mapped fields</strong><span>{Object.entries(lastMapping.fieldMapping).map(([field, header]) => `${titleCase(field)}: ${header || "not mapped"}`).join(" · ")}</span><small>{lastMapping.exceptions.length ? `${lastMapping.exceptions.length} row exceptions held for review: ${lastMapping.exceptions.slice(0, 3).map((item) => `row ${item.rowNumber}`).join(", ")}` : "No row exceptions detected."}</small></div> : null}<div className="core-row-list">{importBatches.length ? importBatches.map((row) => <article key={row.id}><strong>{row.importReference || "Unreferenced Securaze batch"}</strong><span>{row.sourceFileName || "No source file attached"}</span><small>{titleCase(row.status)} · {row.importedRecordCount} mapped assets · {row.exceptionCount} exceptions</small></article>) : <p>No Securaze batches have been recorded.</p>}</div></section>
    </div>
    <div className="core-job-accountability"><section className="core-job-pane"><div className="core-pane-title"><MessageSquareText size={18} /><div><p className="ops-kicker">OPERATOR COMMENTS</p><h4>Keep handoffs in the Core</h4></div></div><textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Add a concise internal note for the next operator." rows={3} /><button className="button button-dark" disabled={comment.trim().length < 2 || addComment.isPending} onClick={() => addComment.mutate({ jobId, brand, comment })}>{addComment.isPending ? <LoaderCircle className="assessment-spin" size={16} /> : <MessageSquareText size={16} />}Add internal comment</button><div className="core-row-list">{comments.length ? comments.map((row) => <article key={row.id}><strong>{row.actorName}</strong><span>{row.comment}</span><small>{new Date(row.createdAt).toLocaleString("en-GB")}</small></article>) : <p>No internal comments yet.</p>}</div></section><section className="core-job-pane core-exception-pane"><div className="core-pane-title"><CircleAlert size={18} /><div><p className="ops-kicker">EXCEPTION OWNERSHIP</p><h4>Open, own and resolve</h4></div></div><div className="core-form-grid"><label className="core-wide">Exception title<input value={exception.title} onChange={(event) => setException({ ...exception, title: event.target.value })} placeholder="What needs operational attention?" /></label><label className="core-wide">Detail<textarea value={exception.detail} onChange={(event) => setException({ ...exception, detail: event.target.value })} placeholder="Optional context for the owner." rows={2} /></label></div><button className="button button-dark" disabled={exception.title.trim().length < 2 || createException.isPending} onClick={() => createException.mutate({ jobId, brand, title: exception.title, detail: exception.detail || undefined })}>{createException.isPending ? <LoaderCircle className="assessment-spin" size={16} /> : <CircleAlert size={16} />}Open and own exception</button><div className="core-row-list">{exceptions.length ? exceptions.map((row) => <article key={row.id}><strong>{row.title}</strong><span>{row.detail || "No additional detail"}</span><small>{row.ownerName} · {titleCase(row.status)}<button onClick={() => updateException.mutate({ exceptionId: row.id, jobId, brand, status: "in_progress", takeOwnership: true })}>Own / progress</button>{row.status !== "resolved" ? <button className="core-approve" onClick={() => updateException.mutate({ exceptionId: row.id, jobId, brand, status: "resolved", takeOwnership: true })}>Resolve</button> : null}</small></article>) : <p>No Core Job exceptions open.</p>}</div></section></div>
    <section className="core-job-activity"><div className="core-pane-title"><History size={18} /><div><p className="ops-kicker">CORE JOB ACTIVITY</p><h4>Attributable operating history</h4></div></div>{activity.length ? <div className="core-activity-list">{activity.map((event) => <article key={event.id}><i /><div><strong>{event.summary}</strong><span>{event.actorName} · {titleCase(event.eventType)}</span></div><time>{new Date(event.createdAt).toLocaleString("en-GB")}</time></article>)}</div> : <p className="core-activity-empty">No Core Job activity has been recorded yet.</p>}</section>
  </section>;
}
