/** Shared UI for the deeper ITAD Core Job records. Brand is always passed explicitly by the consuming workspace. */
import { CheckCircle2, DatabaseZap, Download, FileCheck2, LoaderCircle, PackagePlus, ShieldCheck, Upload } from "lucide-react";
import { ChangeEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { fileToBase64, resolveItadContentType } from "@/lib/itadFiles";

type ItadBrand = "reborn" | "bulk_gsm";
type AssetCondition = "unassessed" | "working" | "repairable" | "parts_only" | "recycling";
type EvidenceType = "data_erasure" | "collection_manifest" | "reuse_outcome" | "recycling_outcome" | "other";

const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const formatCount = (value: number) => new Intl.NumberFormat("en-GB").format(value);

export function CoreJobRecordsPanel({ jobId, brand, workspace }: { jobId: number; brand: ItadBrand; workspace: "Reborn" | "Bulk GSM" }) {
  const utils = trpc.useUtils();
  const detailInput = useMemo(() => ({ jobId, brand }), [jobId, brand]);
  const detail = trpc.itadCore.detail.useQuery(detailInput);
  const [asset, setAsset] = useState({ assetCategory: "", manufacturer: "", model: "", assetTag: "", serialNumber: "", quantity: 1, condition: "unassessed" as AssetCondition, dataHandlingState: "not_recorded" as const });
  const [evidence, setEvidence] = useState({ evidenceType: "data_erasure" as EvidenceType, certificateReference: "", issuer: "", customerVisible: false, file: null as File | null });
  const [importBatch, setImportBatch] = useState({ importReference: "", reportedRecordCount: "", file: null as File | null });
  const refresh = () => utils.itadCore.detail.invalidate(detailInput);
  const addAsset = trpc.itadCore.addAsset.useMutation({ onSuccess: () => { refresh(); setAsset({ assetCategory: "", manufacturer: "", model: "", assetTag: "", serialNumber: "", quantity: 1, condition: "unassessed", dataHandlingState: "not_recorded" }); toast("Asset inventory row added"); }, onError: (error) => toast("Asset inventory was not saved", { description: error.message }) });
  const recordEvidence = trpc.itadCore.recordEvidence.useMutation({ onSuccess: () => { refresh(); setEvidence({ evidenceType: "data_erasure", certificateReference: "", issuer: "", customerVisible: false, file: null }); toast("Evidence record added", { description: "It remains an internal workflow record until reviewed." }); }, onError: (error) => toast("Evidence record was not saved", { description: error.message }) });
  const recordImport = trpc.itadCore.recordSecurazeImport.useMutation({ onSuccess: () => { refresh(); setImportBatch({ importReference: "", reportedRecordCount: "", file: null }); toast("Securaze import batch recorded", { description: "The export is held for review; no data-erasure result is assumed." }); }, onError: (error) => toast("Securaze batch was not recorded", { description: error.message }) });
  const downloadEvidence = trpc.itadCore.downloadEvidence.useMutation({ onSuccess: ({ url }) => window.open(url, "_blank", "noopener,noreferrer"), onError: (error) => toast("Evidence file could not be opened", { description: error.message }) });
  const readFile = (setter: (file: File | null) => void) => (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0] ?? null; if (file?.size && file.size > 10_000_000) { toast("File is too large", { description: "Use a file of 10 MB or less." }); event.target.value = ""; return; } setter(file); };
  const submitEvidence = async () => {
    try {
      const file = evidence.file ? { fileName: evidence.file.name, contentType: resolveItadContentType(evidence.file), contentBase64: await fileToBase64(evidence.file) } : undefined;
      recordEvidence.mutate({ jobId, brand, evidenceType: evidence.evidenceType, certificateReference: evidence.certificateReference || undefined, issuer: evidence.issuer || undefined, customerVisible: evidence.customerVisible, file });
    } catch (error) { toast("Evidence file could not be read", { description: error instanceof Error ? error.message : "Try a different file." }); }
  };
  const submitImport = async () => {
    try {
      const file = importBatch.file ? { fileName: importBatch.file.name, contentType: resolveItadContentType(importBatch.file), contentBase64: await fileToBase64(importBatch.file) } : undefined;
      recordImport.mutate({ jobId, brand, importReference: importBatch.importReference || undefined, reportedRecordCount: importBatch.reportedRecordCount ? Number(importBatch.reportedRecordCount) : undefined, file });
    } catch (error) { toast("Import file could not be read", { description: error instanceof Error ? error.message : "Try a different file." }); }
  };

  if (detail.isLoading) return <section className="core-job-records core-job-loading"><LoaderCircle className="assessment-spin" size={19} />Opening Core Job records</section>;
  if (!detail.data) return <section className="core-job-records core-job-loading">Core Job records are not available right now.</section>;
  const { job, assets, evidence: evidenceRows, importBatches } = detail.data;
  const totalAssets = assets.reduce((total, row) => total + row.quantity, 0);

  return <section className="core-job-records" aria-label={`${workspace} Core Job records`}>
    <header className="core-job-records-head"><div><p className="ops-kicker">ITAD CORE / JOB {job.jobReference}</p><h3>Inventory, evidence <em>and review.</em></h3><p>{workspace} controls these records in its own brand partition. Evidence states describe the review workflow; they do not make a compliance claim.</p></div><div className="core-job-counts"><span><PackagePlus size={16} />{formatCount(totalAssets)} assets</span><span><FileCheck2 size={16} />{evidenceRows.length} evidence</span><span><DatabaseZap size={16} />{importBatches.length} imports</span></div></header>
    <div className="core-job-ledger">
      <section className="core-job-pane"><div className="core-pane-title"><PackagePlus size={18} /><div><p className="ops-kicker">ASSET INVENTORY</p><h4>Add a batch or identified asset</h4></div></div><div className="core-form-grid"><label>Asset category<input value={asset.assetCategory} onChange={(event) => setAsset({ ...asset, assetCategory: event.target.value })} placeholder="Laptop, mobile, monitor" /></label><label>Quantity<input type="number" min="1" value={asset.quantity} onChange={(event) => setAsset({ ...asset, quantity: Math.max(1, Number(event.target.value) || 1) })} /></label><label>Condition<select value={asset.condition} onChange={(event) => setAsset({ ...asset, condition: event.target.value as AssetCondition })}>{["unassessed", "working", "repairable", "parts_only", "recycling"].map((value) => <option key={value} value={value}>{titleCase(value)}</option>)}</select></label><label>Manufacturer<input value={asset.manufacturer} onChange={(event) => setAsset({ ...asset, manufacturer: event.target.value })} placeholder="Optional" /></label><label>Model<input value={asset.model} onChange={(event) => setAsset({ ...asset, model: event.target.value })} placeholder="Optional" /></label><label>Asset tag<input value={asset.assetTag} onChange={(event) => setAsset({ ...asset, assetTag: event.target.value })} placeholder="Optional" /></label><label className="core-wide">Serial number<input value={asset.serialNumber} onChange={(event) => setAsset({ ...asset, serialNumber: event.target.value })} placeholder="Optional — one row can also represent a quantity batch" /></label></div><button className="button button-dark" disabled={!asset.assetCategory || addAsset.isPending} onClick={() => addAsset.mutate({ jobId, brand, ...asset, manufacturer: asset.manufacturer || undefined, model: asset.model || undefined, assetTag: asset.assetTag || undefined, serialNumber: asset.serialNumber || undefined })}>{addAsset.isPending ? <LoaderCircle className="assessment-spin" size={16} /> : <PackagePlus size={16} />}Add inventory row</button><div className="core-row-list">{assets.length ? assets.map((row) => <article key={row.id}><strong>{row.quantity}× {row.assetCategory}</strong><span>{[row.manufacturer, row.model, row.assetTag, row.serialNumber].filter(Boolean).join(" · ") || "No identifier supplied"}</span><small>{titleCase(row.condition)} · {titleCase(row.dataHandlingState)}</small></article>) : <p>No structured assets recorded yet.</p>}</div></section>
      <section className="core-job-pane"><div className="core-pane-title"><ShieldCheck size={18} /><div><p className="ops-kicker">EVIDENCE CERTIFICATES</p><h4>Record, attach, then review</h4></div></div><div className="core-form-grid"><label>Evidence type<select value={evidence.evidenceType} onChange={(event) => setEvidence({ ...evidence, evidenceType: event.target.value as EvidenceType })}>{["data_erasure", "collection_manifest", "reuse_outcome", "recycling_outcome", "other"].map((value) => <option key={value} value={value}>{titleCase(value)}</option>)}</select></label><label>Certificate reference<input value={evidence.certificateReference} onChange={(event) => setEvidence({ ...evidence, certificateReference: event.target.value })} placeholder="Optional reference" /></label><label className="core-wide">Issuer<input value={evidence.issuer} onChange={(event) => setEvidence({ ...evidence, issuer: event.target.value })} placeholder="Optional issuer" /></label><label className="core-file-input">Attach supporting file<input type="file" accept=".pdf,.csv,.xls,.xlsx,.docx,.jpg,.jpeg,.png" onChange={readFile((file) => setEvidence({ ...evidence, file }))} /><span>{evidence.file ? evidence.file.name : "Optional PDF, spreadsheet, Word or image"}</span></label><label className="core-check"><input type="checkbox" checked={evidence.customerVisible} onChange={(event) => setEvidence({ ...evidence, customerVisible: event.target.checked })} />Customer-visible when ready</label></div><button className="button button-dark" disabled={recordEvidence.isPending} onClick={submitEvidence}>{recordEvidence.isPending ? <LoaderCircle className="assessment-spin" size={16} /> : <ShieldCheck size={16} />}Record evidence</button><div className="core-row-list">{evidenceRows.length ? evidenceRows.map((row) => <article key={row.id}><strong>{titleCase(row.evidenceType)}</strong><span>{[row.certificateReference, row.issuer].filter(Boolean).join(" · ") || "No certificate reference or issuer supplied"}</span><small><CheckCircle2 size={13} />{titleCase(row.verificationState)}{row.fileName ? <button onClick={() => downloadEvidence.mutate({ evidenceId: row.id, jobId, brand })}><Download size={13} />{row.fileName}</button> : null}</small></article>) : <p>No evidence records have been added.</p>}</div></section>
      <section className="core-job-pane core-import-pane"><div className="core-pane-title"><DatabaseZap size={18} /><div><p className="ops-kicker">SECURAZE INTAKE</p><h4>Hold an export for review</h4></div></div><p className="core-caution">This records an export and its stated counts. It does not parse or certify an erasure result automatically.</p><div className="core-form-grid"><label>Import reference<input value={importBatch.importReference} onChange={(event) => setImportBatch({ ...importBatch, importReference: event.target.value })} placeholder="Optional batch reference" /></label><label>Reported record count<input type="number" min="0" value={importBatch.reportedRecordCount} onChange={(event) => setImportBatch({ ...importBatch, reportedRecordCount: event.target.value })} placeholder="Optional" /></label><label className="core-file-input core-wide">Securaze export<input type="file" accept=".csv,.xls,.xlsx" onChange={readFile((file) => setImportBatch({ ...importBatch, file }))} /><span>{importBatch.file ? importBatch.file.name : "Optional CSV or spreadsheet export"}</span></label></div><button className="button button-lime" disabled={recordImport.isPending} onClick={submitImport}>{recordImport.isPending ? <LoaderCircle className="assessment-spin" size={16} /> : <Upload size={16} />}Record Securaze batch</button><div className="core-row-list">{importBatches.length ? importBatches.map((row) => <article key={row.id}><strong>{row.importReference || "Unreferenced Securaze batch"}</strong><span>{row.sourceFileName || "No source file attached"}</span><small>{titleCase(row.status)} · {row.reportedRecordCount ?? "—"} reported · {row.exceptionCount} exceptions</small></article>) : <p>No Securaze batches have been recorded.</p>}</div></section>
    </div>
  </section>;
}
